# Generated by Django 2.0.5 on 2018-05-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='曲名')),
                ('singer_name', models.CharField(max_length=200, verbose_name='歌手名')),
                ('anime_title', models.CharField(max_length=100, verbose_name='アニメタイトル')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='song_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.Song', verbose_name='曲名'),
        ),
    ]
