# Generated by Django 2.0.5 on 2018-05-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('song_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='myapp.Song', verbose_name='曲名')),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='song_name',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
